#!/opt/rbenv/shims/ruby

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

chdir APP_ROOT do
  # This script is a starting point to setup your application.
  # Add necessary setup steps to this file.

  puts '== Setup =='
  system! 'bin/setup'

  puts "\n== Remove sockets =="
  system! 'rm -f tmp/sockets/*'
  system! 'rm -f tmp/pids/*'

  puts "\n== Database Preparing =="
  system! 'bundle exec rails db:drop'
  system! 'bundle exec rails db:create'
  system! 'bundle exec rails db:migrate'
  system! 'bundle exec rails db:migrate RAILS_ENV=test'
  #system! 'bin/reset-db-migrate'

  puts "\n== Launch unicorn =="
  system! 'bundle exec unicorn -c config/unicorn/development.rb -E development'

  puts "\n== Setting up docker-web done =="
end
